# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Splash_Screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide2 import QtCore, QtGui, QtWidgets


class Ui_SplashScreen(object):
    def setupUi(self, SplashScreen):
        SplashScreen.setObjectName("SplashScreen")
        SplashScreen.resize(804, 403)
        self.centralwidget = QtWidgets.QWidget(SplashScreen)
        self.centralwidget.setMinimumSize(QtCore.QSize(800, 400))
        self.centralwidget.setMaximumSize(QtCore.QSize(800, 400))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout.setSpacing(3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.DropShadowFrame = QtWidgets.QFrame(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("MS PGothic")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.DropShadowFrame.setFont(font)
        self.DropShadowFrame.setStyleSheet("QFrame {\n"
"    background-color: rgb(53, 4, 10);\n"
"    color: rgb(252, 72, 90);\n"
"    border-radius: 12px\n"
"}")
        self.DropShadowFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.DropShadowFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.DropShadowFrame.setObjectName("DropShadowFrame")
        self.AppName = QtWidgets.QLabel(self.DropShadowFrame)
        self.AppName.setGeometry(QtCore.QRect(0, 20, 791, 111))
        font = QtGui.QFont()
        font.setFamily("Creepsville")
        font.setPointSize(45)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.AppName.setFont(font)
        self.AppName.setStyleSheet("color: rgb(159, 8, 23)")
        self.AppName.setAlignment(QtCore.Qt.AlignCenter)
        self.AppName.setObjectName("AppName")
        self.AppDesc = QtWidgets.QLabel(self.DropShadowFrame)
        self.AppDesc.setGeometry(QtCore.QRect(0, 120, 801, 41))
        font = QtGui.QFont()
        font.setFamily("CF Night of Terror PERSONAL")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.AppDesc.setFont(font)
        self.AppDesc.setStyleSheet("color: rgba(135, 42, 70, 220);")
        self.AppDesc.setAlignment(QtCore.Qt.AlignCenter)
        self.AppDesc.setObjectName("AppDesc")
        self.ProgressBar = QtWidgets.QProgressBar(self.DropShadowFrame)
        self.ProgressBar.setGeometry(QtCore.QRect(70, 270, 671, 23))
        self.ProgressBar.setStyleSheet("QProgressBar {\n"
"    color: rgb(214, 220, 210);\n"
"    background-color: rgba(85, 6, 16, 200);\n"
"    border-style: none;\n"
"    border: 5px qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(158, 7, 23, 255), stop:1 rgba(255, 130, 20, 255));\n"
"    border-radius: 10px;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    border-radius: 10px;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(253, 128, 20, 255), stop:1 rgba(159, 8, 23, 255));\n"
"}")
        self.ProgressBar.setProperty("value", 24)
        self.ProgressBar.setObjectName("ProgressBar")
        self.LoadingStatus = QtWidgets.QLabel(self.DropShadowFrame)
        self.LoadingStatus.setGeometry(QtCore.QRect(0, 300, 791, 21))
        font = QtGui.QFont()
        font.setFamily("CF Night of Terror PERSONAL")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.LoadingStatus.setFont(font)
        self.LoadingStatus.setStyleSheet("color: qlineargradient(spread:pad, x1:0.248473, y1:0.483, x2:1, y2:0, stop:0.208955 rgba(131, 62, 40, 231), stop:1 rgba(163, 13, 23, 248));")
        self.LoadingStatus.setAlignment(QtCore.Qt.AlignCenter)
        self.LoadingStatus.setObjectName("LoadingStatus")
        self.CreatedBy = QtWidgets.QLabel(self.DropShadowFrame)
        self.CreatedBy.setGeometry(QtCore.QRect(320, 370, 461, 16))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.CreatedBy.setFont(font)
        self.CreatedBy.setStyleSheet("color: qlineargradient(spread:pad, x1:0.248473, y1:0.483, x2:1, y2:0, stop:0.208955 rgba(131, 62, 40, 231), stop:1 rgba(163, 13, 23, 248));\n"
"border-radius: 100px;")
        self.CreatedBy.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.CreatedBy.setObjectName("CreatedBy")
        self.Version = QtWidgets.QLabel(self.DropShadowFrame)
        self.Version.setGeometry(QtCore.QRect(10, 0, 55, 16))
        self.Version.setStyleSheet("border: 0px solid;\n"
"border-radius: 10px;")
        self.Version.setObjectName("Version")
        self.verticalLayout.addWidget(self.DropShadowFrame)
        SplashScreen.setCentralWidget(self.centralwidget)

        self.retranslateUi(SplashScreen)
        QtCore.QMetaObject.connectSlotsByName(SplashScreen)

    def retranslateUi(self, SplashScreen):
        _translate = QtCore.QCoreApplication.translate
        SplashScreen.setWindowTitle(_translate("SplashScreen", "MainWindow"))
        self.AppName.setText(_translate("SplashScreen", "Thor<strong>𝜓vos</strong>"))
        self.AppDesc.setText(_translate("SplashScreen", "The all in one audio cryptographic toolkit"))
        self.LoadingStatus.setText(_translate("SplashScreen", "Loading..."))
        self.CreatedBy.setText(_translate("SplashScreen", "Made By: Rakshan Sharma"))
        self.Version.setText(_translate("SplashScreen", "V1.0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SplashScreen = QtWidgets.QMainWindow()
    ui = Ui_SplashScreen()
    ui.setupUi(SplashScreen)
    SplashScreen.show()
    sys.exit(app.exec_())
